package com.hallak.SettlementApp.dtos;

public enum BetType {
    MILHAR_SECA,
    MILHAR_CERCADA,
    MILHAR_INVERTIDA_SECA,
    MILHAR_INVERTIDA_CERCADA,
    CENTENA_SECA,
    CENTENA_CERCADA,
    CENTENA_INVERTIDA_SECA,
    CENTENA_INVERTIDA_CERCADA,
    DEZENA_SECA,
    DEZENA_CERCADA,
    DEZENA_INVERTIDA_SECA,
    DEZENA_INVERTIDA_CERCADA,
    DUQUE_DE_DEZENA,
    TERNO_DE_DEZENA,
    GRUPO_SECO,
    GRUPO_CERCADO,
    DUPLA_DE_GRUPO_SECO,
    DUPLA_DE_GRUPO_CERCADO,
    TERNO_DE_GRUPO_SECO,
    TERNO_DE_GRUPO_CERCADO,
    PASSE_SECO,
    PASSE_CERCADO,
    PASSE_INVERTIDO_SECO,
    PASSE_INVERTIDO_CERCADO;
}