INSERT INTO tb_house(username, password) VALUES ('casa1', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');
INSERT INTO tb_house(username, password) VALUES ('casa2', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');
INSERT INTO tb_house(username, password) VALUES ('casa3', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');
INSERT INTO tb_house(username, password) VALUES ('casa4', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');
INSERT INTO tb_house(username, password) VALUES ('casa5', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');
INSERT INTO tb_house(username, password) VALUES ('casa6', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');
INSERT INTO tb_house(username, password) VALUES ('casa7', '$2a$12$AlnbeLG./9yRd4UVGkpRu.NaBKVnRRv/DdOyX2JYq.kTpNEH1EnkC');

INSERT INTO tb_game(name, creation_date, capture_date, status, house_id) VALUES ('Game 3', '2025-05-10T10:00:00', '2025-05-11T12:00:00', true, 3);
INSERT INTO tb_game(name, creation_date, capture_date, status, house_id) VALUES ('Game 4', '2025-05-10T11:00:00', '2025-05-11T13:00:00', true, 4);
INSERT INTO tb_game(name, creation_date, capture_date, status, house_id) VALUES ('Game 5', '2025-05-10T12:00:00', '2025-05-11T14:00:00', true, 5);
INSERT INTO tb_game(name, creation_date, capture_date, status, house_id) VALUES ('Game 6', '2025-05-10T13:00:00', '2025-06-11T15:00:00', true, 6);
INSERT INTO tb_game(name, creation_date, capture_date, status, house_id) VALUES ('Game 7', '2025-05-10T14:00:00', '2025-06-11T16:00:00', true, 7);
INSERT INTO tb_game(name, creation_date, capture_date, status, house_id)VALUES ('Game 1', '2025-05-08T14:00:00', '2025-05-09T12:00:00', true, 1);
INSERT INTO tb_game(name, creation_date, capture_date, status, house_id)VALUES ('Game 2', '2025-05-08T15:00:00', '2025-05-09T13:00:00', true, 2);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'MILHAR_SECA', 1.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'MILHAR_CERCADA', 2.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'MILHAR_INVERTIDA', 2.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'CENTENA_SECA', 1.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'CENTENA_CERCADA', 2.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'CENTENA_INVERTIDA', 2.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'DEZENA_SECA', 1.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'DEZENA_CERCADA', 2.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'DEZENA_INVERTIDA', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'DUQUE_DE_DEZENA', 3.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'TERNO_DE_DEZENA', 3.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'GRUPO_SECO', 1.8);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'GRUPO_CERCADO', 2.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'DUPLA_DE_GRUPO_SECO', 3.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'DUPLA_DE_GRUPO_CERCADO', 3.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'TERNO_DE_GRUPO_SECO', 4.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'TERNO_DE_GRUPO_CERCADO', 4.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'PASSE', 1.9);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (1, 'PASSE_INVERTIDO', 2.6);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'MILHAR_SECA', 1.8);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'MILHAR_CERCADA', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'MILHAR_INVERTIDA', 2.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'CENTENA_SECA', 1.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'CENTENA_CERCADA', 2.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'CENTENA_INVERTIDA', 2.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'DEZENA_SECA', 1.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'DEZENA_CERCADA', 2.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'DEZENA_INVERTIDA', 2.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'DUQUE_DE_DEZENA', 3.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'TERNO_DE_DEZENA', 3.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'GRUPO_SECO', 1.9);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'GRUPO_CERCADO', 2.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'DUPLA_DE_GRUPO_SECO', 3.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'DUPLA_DE_GRUPO_CERCADO', 3.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'TERNO_DE_GRUPO_SECO', 4.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'TERNO_DE_GRUPO_CERCADO', 4.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'PASSE', 2.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (2, 'PASSE_INVERTIDO', 2.7);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'MILHAR_SECA', 1.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'MILHAR_CERCADA', 2.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'MILHAR_INVERTIDA', 2.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'CENTENA_SECA', 1.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'CENTENA_CERCADA', 2.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'CENTENA_INVERTIDA', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'DEZENA_SECA', 1.8);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'DEZENA_CERCADA', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'DEZENA_INVERTIDA', 2.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'DUQUE_DE_DEZENA', 3.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'TERNO_DE_DEZENA', 3.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'GRUPO_SECO', 1.85);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'GRUPO_CERCADO', 2.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'DUPLA_DE_GRUPO_SECO', 3.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'DUPLA_DE_GRUPO_CERCADO', 3.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'TERNO_DE_GRUPO_SECO', 4.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'TERNO_DE_GRUPO_CERCADO', 4.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'PASSE', 2.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (3, 'PASSE_INVERTIDO', 2.8);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'MILHAR_SECA', 1.55);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'MILHAR_CERCADA', 2.05);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'MILHAR_INVERTIDA', 2.45);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'CENTENA_SECA', 1.65);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'CENTENA_CERCADA', 2.15);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'CENTENA_INVERTIDA', 2.55);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'DEZENA_SECA', 1.75);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'DEZENA_CERCADA', 2.25);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'DEZENA_INVERTIDA', 2.35);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'DUQUE_DE_DEZENA', 3.15);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'TERNO_DE_DEZENA', 3.65);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'GRUPO_SECO', 1.85);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'GRUPO_CERCADO', 2.55);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'DUPLA_DE_GRUPO_SECO', 3.25);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'DUPLA_DE_GRUPO_CERCADO', 3.45);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'TERNO_DE_GRUPO_SECO', 4.15);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'TERNO_DE_GRUPO_CERCADO', 4.35);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'PASSE', 2.05);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (4, 'PASSE_INVERTIDO', 2.65);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'MILHAR_SECA', 1.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'MILHAR_CERCADA', 2.1);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'MILHAR_INVERTIDA', 2.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'CENTENA_SECA', 1.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'CENTENA_CERCADA', 2.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'CENTENA_INVERTIDA', 2.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'DEZENA_SECA', 1.8);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'DEZENA_CERCADA', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'DEZENA_INVERTIDA', 2.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'DUQUE_DE_DEZENA', 3.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'TERNO_DE_DEZENA', 3.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'GRUPO_SECO', 1.9);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'GRUPO_CERCADO', 2.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'DUPLA_DE_GRUPO_SECO', 3.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'DUPLA_DE_GRUPO_CERCADO', 3.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'TERNO_DE_GRUPO_SECO', 4.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'TERNO_DE_GRUPO_CERCADO', 4.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'PASSE', 2.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (5, 'PASSE_INVERTIDO', 2.9);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'MILHAR_SECA', 1.65);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'MILHAR_CERCADA', 2.15);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'MILHAR_INVERTIDA', 2.55);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'CENTENA_SECA', 1.75);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'CENTENA_CERCADA', 2.25);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'CENTENA_INVERTIDA', 2.65);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'DEZENA_SECA', 1.85);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'DEZENA_CERCADA', 2.35);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'DEZENA_INVERTIDA', 2.45);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'DUQUE_DE_DEZENA', 3.25);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'TERNO_DE_DEZENA', 3.75);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'GRUPO_SECO', 1.95);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'GRUPO_CERCADO', 2.65);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'DUPLA_DE_GRUPO_SECO', 3.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'DUPLA_DE_GRUPO_CERCADO', 3.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'TERNO_DE_GRUPO_SECO', 4.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'TERNO_DE_GRUPO_CERCADO', 4.6);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'PASSE', 2.25);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (6, 'PASSE_INVERTIDO', 2.95);

INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'MILHAR_SECA', 1.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'MILHAR_CERCADA', 2.2);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'MILHAR_INVERTIDA', 2.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'CENTENA_SECA', 1.8);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'CENTENA_CERCADA', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'CENTENA_INVERTIDA', 2.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'DEZENA_SECA', 1.9);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'DEZENA_CERCADA', 2.4);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'DEZENA_INVERTIDA', 2.55);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'DUQUE_DE_DEZENA', 3.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'TERNO_DE_DEZENA', 3.8);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'GRUPO_SECO', 2.0);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'GRUPO_CERCADO', 2.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'DUPLA_DE_GRUPO_SECO', 3.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'DUPLA_DE_GRUPO_CERCADO', 3.75);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'TERNO_DE_GRUPO_SECO', 4.5);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'TERNO_DE_GRUPO_CERCADO', 4.7);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'PASSE', 2.3);
INSERT INTO house_odds(house_id, bet_type, value) VALUES (7, 'PASSE_INVERTIDO', 3.0);


INSERT INTO tb_role(id, authority) VALUES (1, 'ROLE_USER');

INSERT INTO tb_house_role (house_id, role_id) VALUES (1, 1);
INSERT INTO tb_house_role (house_id, role_id) VALUES (2, 1);
INSERT INTO tb_house_role (house_id, role_id) VALUES (3, 1);
INSERT INTO tb_house_role (house_id, role_id) VALUES (4, 1);
INSERT INTO tb_house_role (house_id, role_id) VALUES (5, 1);
INSERT INTO tb_house_role (house_id, role_id) VALUES (6, 1);
INSERT INTO tb_house_role (house_id, role_id) VALUES (7, 1);

